spring:
  application:
    name: cuidarplus
  datasource:
    url: jdbc:mysql://localhost:3306/cuidarplus
    username: root
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: false
